server:
  port: 9191
  tomcat:
    uri-encoding: UTF-8
  servlet:
    session:
      timeout: 30m     #session过期时间

spring:
  resources:
    static-locations: classpath:/static        #静态资源路径设置
  datasource:
    name: mysql_vm
    type: com.alibaba.druid.pool.DruidDataSource
    #druid相关配置
    druid:
      #监控统计拦截的filters
      filters: stat
      #6.0以上mysql
      driver-class-name: com.mysql.cj.jdbc.Driver
      #基本属性
      url: jdbc:mysql://10.30.17.153:3306/vm?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC

      #5其他版本mysql
      #driver-class-name: com.mysql.jdbc.Driver
      #基本属性
      #url: jdbc:mysql://10.30.17.145:3306/vm?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
      username: root
      password: Abcd@1234
      #配置初始化大小/最小/最大
      initial-size: 1
      min-idle: 1
      max-active: 20
      #获取连接等待超时时间
      max-wait: 60000
      #间隔多久进行一次检测，检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000
      #一个连接在池中最小生存的时间
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
  http:
    encoding:
      charset: utf-8
      force: true
      enabled: true
  thymeleaf:
    cache: false #开发配置为false 避免修改模板还要重启服务器
    mode: HTML5 #模板模式,支持HTML,XML,TEXT,JAVASCRIPT
    suffix: .html #配置后缀名
  devtools: #热部署配置
    restart:
      enabled: true
    livereload:
      enabled: true
      port: 35729
### mybatis配置
#mybatis:
#  mapper-locations: classpath:mappers/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
#  type-aliases-package: com.ch.vm.model
#  configuration:
#    map-underscore-to-camel-case: true # 注意：对应实体类的路径
# mybatis-plus相关配置
mybatis-plus:
  # xml扫描，多个目录用逗号或者分号分隔（告诉 Mapper 所对应的 XML 文件位置）
  mapper-locations: classpath:mappers/*.xml
  # 以下配置均有默认值,可以不设置
  global-config:
    db-config:
      #主键类型  auto:"数据库ID自增" 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      id-type: auto
      #字段策略 IGNORED:"忽略判断"  NOT_NULL:"非 NULL 判断")  NOT_EMPTY:"非空判断"
      field-strategy: NOT_EMPTY
      #数据库类型
      db-type: MYSQL
  configuration:
    # 是否开启自动驼峰命名规则映射:从数据库列名到Java属性驼峰命名的类似映射
    map-underscore-to-camel-case: true
    # 如果查询结果中包含空值的列，则 MyBatis 在映射的时候，不会映射这个字段
    call-setters-on-nulls: true
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  returnPageInfo: check

  #日志设置
#logging:
 # config: classpath:logback-spring-dev.xml
